### PR TITLE
Added date validation for birth date

### PR DESCRIPTION
**Pull request by kwyoke**
Used regex and html5 pattern attribute

### CODE REVIEW

**Review by ankurjha21 — CHANGES_REQUESTED** [review]
I have one more suggestion by passing this Regex expression 
var pattern =/^([0-9]{2})\/([0-9]{2})\/([0-9]{4})$/;

**Comment by kwyoke** [comment]
Yep yours is more succinct! I was trying to make the validation more stringent by making sure that dd cannot be more than 31 and mm cannot be more than 12 but didn't quite achieve that exactly

**Comment by jmewes** [comment]
Thank you very much for your contribution.

I like the idea of doing a vanity check for the input data on top of the date format check. However, doing numeric range checks with regular expressions is not possible, just string range checks (see [regular-expressions.info](https://www.regular-expressions.info/numericranges.html)).

I suggest the following improvements on top of your commit:

- Add some more boilerplate HTML code around the panel to be able to test the regular expression (Wicket will only use what is in the panel tag.)
- Allow users to enter single digit numbers for the date and month
- Further restrict the year to start with "1" or "2", instead of also a "0".

See pull request on your pull request: https://github.com/kwyoke/ksch-workflows/pull/1

**Comment by jmewes** [comment]
Regarding the proposal from @ankurjha21 , I have asked a question for clarification here:

https://github.com/ksch-workflows/ksch-workflows/pull/23#issuecomment-434669822

**Comment by jmewes** [comment]
resolve #21

**Pull request merged**
